"""A ``conformance-kit`` line-protocol adapter for the seal and audit-log verifiers (Slice 87).

    python3 -m analystos.conformance            # reads cases on stdin, answers on stdout

Reads one JSON object per line ``{"id", "set", "input"}`` and writes one per line
``{"id", "valid", "codes"}``, the same wire protocol as ``analystos/aao/kit.py``. The corpus is
``conformance/seal-1.json`` (generated by ``tools/build_conformance_corpus.py``); the sets are:

    seal            valid = the bundle is internally consistent (``ok``)
    seal-authentic  valid = ``authentic`` (signature verifies under a key YOU pinned)
    seal-content    valid = ``content_checked`` (checked against the supplied text)
    audit           valid = the audit log verifies (``ok``)
    audit-authentic valid = ``authentic`` (every line signed, all verify under the pinned key)

``codes`` are the names of the checks that failed (plus, for the three stricter levels, the
relevant checks that were only *skipped*, because "not established" is not "established").

A case the verifier crashes on is **not answered** (the traceback goes to stderr, stdout stays a
verdict stream): a crash is a different finding from a wrong verdict and the runner must see it as
one. ``run_corpus`` is the in-process runner used by the test suite; it applies the same four
outcomes as the kit (agreed, disagreed, unanswered, unreadable) and refuses to call a run good
when it executed nothing.
"""

import io
import json
import os
import sys
import tempfile
import traceback
from pathlib import Path

from analystos.api_v1.audit_chain import verify_audit_log
from analystos.l4.seal_verify import verify_bundle, verify_bundle_with_key_file

CORPUS_PATH = Path(__file__).resolve().parents[1] / "conformance" / "seal-1.json"
MIN_REFUSAL_SHARE = 0.60

_SKIPPED_THAT_COUNT = {
    "seal-authentic": {"signature", "key_file"},
    "seal-content": {"source_text_hash", "citations_in_text", "values_match_citations", "calculations"},
    "audit-authentic": {"signatures"},
}
_LEVEL = {"seal": "ok", "seal-authentic": "authentic", "seal-content": "content_checked",
          "audit": "ok", "audit-authentic": "authentic"}


def _codes(outcome, set_name):
    counted = _SKIPPED_THAT_COUNT.get(set_name, set())
    return sorted({c["name"] for c in outcome["checks"] if c["status"] == "fail" or (c["status"] == "skipped" and c["name"] in counted)})


def _run_audit(inp):
    lines = inp["lines"]
    handle, path = tempfile.mkstemp(suffix=".jsonl")
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as out:
            out.write("".join(line + "\n" for line in lines))
        return verify_audit_log(path, public_key=inp.get("public_key"), expected_head=inp.get("expected_head"))
    finally:
        os.unlink(path)


def answer(case):
    """The ``{"id", "valid", "codes"}`` verdict for one case, or raises (the caller leaves it unanswered)."""
    name, inp = case["set"], case["input"]
    if name not in _LEVEL:
        raise KeyError(f"unknown set {name!r}")
    if name.startswith("seal"):
        if inp.get("key_file") is not None:
            outcome = verify_bundle_with_key_file(inp["bundle"], inp["key_file"], source_text=inp.get("source_text"))
        else:
            outcome = verify_bundle(inp["bundle"], public_key=inp.get("public_key"), source_text=inp.get("source_text"))
    else:
        outcome = _run_audit(inp)
    return {"id": case["id"], "valid": bool(outcome[_LEVEL[name]]), "codes": _codes(outcome, name)}


def serve(lines, out, err=None):
    err = err if err is not None else sys.stderr
    for line in lines:
        if not line.strip():
            continue
        try:
            case = json.loads(line)
        except ValueError:
            continue
        if not isinstance(case, dict) or "id" not in case:
            continue
        try:
            verdict = answer(case)
        except Exception:  # noqa: BLE001 - a crash is reported on stderr and left unanswered, never turned into a verdict
            err.write(f"case {case.get('id')!r} crashed the verifier:\n{traceback.format_exc()}")
            continue
        out.write(json.dumps(verdict) + "\n")
        out.flush()


# --- the in-process runner (same judgement rules as the kit) --------------------------------------------

def load_corpus(path=CORPUS_PATH):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def corpus_cases(corpus):
    return [dict(c, set=s["name"]) for s in corpus["sets"] for c in s["cases"]]


def judge(expected, got):
    if got is None:
        return "unanswered"
    if not isinstance(got, dict) or not isinstance(got.get("valid"), bool):
        return "unreadable"
    if got["valid"] != expected["valid"]:
        return "disagreed"
    if isinstance(expected.get("codes"), list) and not set(expected["codes"]) <= set(got.get("codes") or []):
        return "disagreed"
    return "agreed"


def run_corpus(corpus=None):
    """Run every case through the real line protocol. Returns counts, the offending case ids and the refusal share."""
    corpus = corpus or load_corpus()
    cases = corpus_cases(corpus)
    stdin = "".join(json.dumps({"id": c["id"], "set": c["set"], "input": c["input"]}) + "\n" for c in cases)
    out, err = io.StringIO(), io.StringIO()
    serve(io.StringIO(stdin).readlines(), out, err)
    answers = {}
    for line in out.getvalue().splitlines():
        try:
            parsed = json.loads(line)
        except ValueError:
            continue
        if isinstance(parsed, dict) and "id" in parsed:
            answers[parsed["id"]] = parsed
    states = {c["id"]: judge(c["expect"], answers.get(c["id"])) for c in cases}
    count = {s: sum(v == s for v in states.values()) for s in ("agreed", "disagreed", "unanswered", "unreadable")}
    refusals = sum(not c["expect"]["valid"] for c in cases)
    return {
        "total": len(cases), **count,
        "gaps": {c["id"]: c["known_gap"] for c in cases if c.get("known_gap")},
        "bad": {i: s for i, s in states.items() if s != "agreed"},
        "refusal_share": refusals / len(cases) if cases else 0.0,
        "stderr": err.getvalue(),
    }


def problems(report, min_refusal_share=MIN_REFUSAL_SHARE):
    """Everything wrong with a ``run_corpus`` report; empty means the run is clean. A case listed as a
    ``known_gap`` must still fail (so fixing it forces removing the annotation); every other case must agree."""
    found = []
    if not report["total"]:
        found.append("the corpus executed zero cases")
    gaps = report.get("gaps", {})
    for case_id, state in sorted(report["bad"].items()):
        if case_id not in gaps:
            found.append(f"{state}: {case_id}")
    for case_id in sorted(set(gaps) - set(report["bad"])):
        found.append(f"known gap now agrees, remove its annotation: {case_id}")
    if report["refusal_share"] < min_refusal_share:
        found.append(f"refusals are {report['refusal_share']:.0%} of cases, below {min_refusal_share:.0%}")
    return found


if __name__ == "__main__":
    serve(sys.stdin, sys.stdout)
